// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFYxR0zI1LsZvTC7OlwvL3Gn3wcNID6y4',
    appId: '1:572681652958:web:2e32a040c83cc79724d04f',
    messagingSenderId: '572681652958',
    projectId: 'lifetime-ledger',
    authDomain: 'lifetime-ledger.firebaseapp.com',
    storageBucket: 'lifetime-ledger.firebasestorage.app',
    measurementId: 'G-6EPR8EXDSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDq0hPkm8p-qz3Z4TkaMt9AkCTfNjklD8',
    appId: '1:572681652958:android:825aed8009a9beaf24d04f',
    messagingSenderId: '572681652958',
    projectId: 'lifetime-ledger',
    storageBucket: 'lifetime-ledger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6qnoqIHH8R-dqqBr_aGvqYN9uO7vCPnw',
    appId: '1:572681652958:ios:3a56c1004ff5cbb824d04f',
    messagingSenderId: '572681652958',
    projectId: 'lifetime-ledger',
    storageBucket: 'lifetime-ledger.firebasestorage.app',
    iosBundleId: 'com.lifetimeledgerseonho.lifetimeLedger',
  );
}
